/* tslint:disable */
/* eslint-disable */
/**
 * Cashout API
 * Personal finance tracking API. All /api/_* endpoints require either a session cookie (browser) or an Authorization: Bearer <token> header (machine clients).
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WebCategoriesResponse,
  WebCreateTransactionRequest,
  WebDeleteTransactionRequest,
  WebErrorResponse,
  WebMessageResponse,
  WebStatsResponse,
  WebTransactionsResponse,
} from '../models/index';
import {
    WebCategoriesResponseFromJSON,
    WebCategoriesResponseToJSON,
    WebCreateTransactionRequestFromJSON,
    WebCreateTransactionRequestToJSON,
    WebDeleteTransactionRequestFromJSON,
    WebDeleteTransactionRequestToJSON,
    WebErrorResponseFromJSON,
    WebErrorResponseToJSON,
    WebMessageResponseFromJSON,
    WebMessageResponseToJSON,
    WebStatsResponseFromJSON,
    WebStatsResponseToJSON,
    WebTransactionsResponseFromJSON,
    WebTransactionsResponseToJSON,
} from '../models/index';

export interface ApiCategoriesGetRequest {
    type: string;
}

export interface ApiStatsGetRequest {
    month?: string;
}

export interface ApiTransactionsCreatePostRequest {
    body: WebCreateTransactionRequest;
}

export interface ApiTransactionsDeleteDeleteRequest {
    body: WebDeleteTransactionRequest;
}

export interface ApiTransactionsGetRequest {
    month?: string;
}

/**
 * 
 */
export class TransactionsApi extends runtime.BaseAPI {

    /**
     * List categories
     */
    async apiCategoriesGetRaw(requestParameters: ApiCategoriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebCategoriesResponse>> {
        if (requestParameters['type'] == null) {
            throw new runtime.RequiredError(
                'type',
                'Required parameter "type" was null or undefined when calling apiCategoriesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/categories`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebCategoriesResponseFromJSON(jsonValue));
    }

    /**
     * List categories
     */
    async apiCategoriesGet(requestParameters: ApiCategoriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebCategoriesResponse> {
        const response = await this.apiCategoriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Monthly stats
     */
    async apiStatsGetRaw(requestParameters: ApiStatsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebStatsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebStatsResponseFromJSON(jsonValue));
    }

    /**
     * Monthly stats
     */
    async apiStatsGet(requestParameters: ApiStatsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebStatsResponse> {
        const response = await this.apiStatsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create transaction
     */
    async apiTransactionsCreatePostRaw(requestParameters: ApiTransactionsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebMessageResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiTransactionsCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/transactions/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebCreateTransactionRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebMessageResponseFromJSON(jsonValue));
    }

    /**
     * Create transaction
     */
    async apiTransactionsCreatePost(requestParameters: ApiTransactionsCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebMessageResponse> {
        const response = await this.apiTransactionsCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete transaction
     */
    async apiTransactionsDeleteDeleteRaw(requestParameters: ApiTransactionsDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebMessageResponse>> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling apiTransactionsDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/transactions/delete`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: WebDeleteTransactionRequestToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebMessageResponseFromJSON(jsonValue));
    }

    /**
     * Delete transaction
     */
    async apiTransactionsDeleteDelete(requestParameters: ApiTransactionsDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebMessageResponse> {
        const response = await this.apiTransactionsDeleteDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List transactions for a month
     */
    async apiTransactionsGetRaw(requestParameters: ApiTransactionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebTransactionsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }


        let urlPath = `/api/transactions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebTransactionsResponseFromJSON(jsonValue));
    }

    /**
     * List transactions for a month
     */
    async apiTransactionsGet(requestParameters: ApiTransactionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebTransactionsResponse> {
        const response = await this.apiTransactionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
